config/routes.rb
Rails.application.routes.draw do
 
  resources :product_features
  resources :pfeatures
  resources :products
  resources :roles
  
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "home#index"

  get 'home/index'

  get 'home/about'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  
  validates :name, presence: true, uniqueness: true 

  def to_s
    # show columns contents, not record object like: 	#<Vehicle:0x007f343b3f2890>	2016-06-08	
    # http://stackoverflow.com/questions/4829909/how-do-i-print-out-the-contents-of-an-object-in-rails-for-easy-debugging
    #"Name:#{self.name} Age:#{self.age} Weight: #{self.weight}"
    "#{name}"
  end

   
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  #cancancan
  load_and_authorize_resource

  # GET /roles
  def index
    # @roles = Role.all
    @q = Role.search(params[:q]) 
    @roles = @q.result.page(params[:page])
  end

  # GET /roles/1
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role, notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /roles/1
  def update
    if @role.update(role_params)
      redirect_to @role, notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /roles/1
  def destroy
    @role.destroy
    redirect_to roles_url, notice: 'Role was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def role_params
      params.require(:role).permit(:name, :description, :active_status, :sort)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= simple_form_for(@role) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :active_status %>
    <%= f.input :sort %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<row>

  <div class="col-sm-2 ">
    <h3>Listing Roles</h3>
  </div>

  <div class="col-sm-3 col-sm-offset-1">
    <%= search_form_for @q, class: 'search-form' do |f| %>
      <div class="input-group">
        <%= f.search_field :name_cont, class: 'form-control' %>
        <span class="input-group-btn">
          <button class="btn btn-primary">Search <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-5 ">
    <%= paginate @roles %>
  </div>
  
</row>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Active status</th>
      <th>Sort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= role.active_status %></td>
        <td><%= role.sort %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @role.active_status %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @role.sort %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>