config/routes.rb
Rails.application.routes.draw do
 
  resources :product_features
  resources :pfeatures
  resources :products
  resources :roles
  
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "home#index"

  get 'home/index'

  get 'home/about'

end

app/models/product_feature.rb
class ProductFeature < ActiveRecord::Base
  belongs_to :product
  belongs_to :pfeature
end

app/controllers/product_features_controller.rb
class ProductFeaturesController < ApplicationController
  before_action :set_product_feature, only: [:show, :edit, :update, :destroy]

  #cancancan
  load_and_authorize_resource

  # GET /product_features
  def index
    # @product_features = ProductFeature.all
    @q = ProductFeature.search(params[:q]) 
    @product_features = @q.result.page(params[:page])
  end

  # GET /product_features/1
  def show
  end

  # GET /product_features/new
  def new
    @product_feature = ProductFeature.new
  end

  # GET /product_features/1/edit
  def edit
  end

  # POST /product_features
  def create
    @product_feature = ProductFeature.new(product_feature_params)

    if @product_feature.save
      redirect_to @product_feature, notice: 'Product feature was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /product_features/1
  def update
    if @product_feature.update(product_feature_params)
      redirect_to @product_feature, notice: 'Product feature was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /product_features/1
  def destroy
    @product_feature.destroy
    redirect_to product_features_url, notice: 'Product feature was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_feature
      @product_feature = ProductFeature.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_feature_params
      params.require(:product_feature).permit(:name, :product_id, :pfeature_id, :active_status, :sort)
    end
end

app/helpers/product_features_helper.rb
module ProductFeaturesHelper
end

app/views/product_features/_form.html.erb
<%= simple_form_for(@product_feature) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :product %>
    <%= f.association :pfeature %>
    <%= f.input :active_status %>
    <%= f.input :sort %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/product_features/edit.html.erb
<h1>Editing Product Feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_feature %> |
<%= link_to 'Back', product_features_path %>

app/views/product_features/index.html.erb
<p id="notice"><%= notice %></p>

<row>

  <div class="col-sm-2 ">
    <h3>Listing Product Features</h3>
  </div>

  <div class="col-sm-3 col-sm-offset-1">
    <%= search_form_for @q, class: 'search-form' do |f| %>
      <div class="input-group">
        <%= f.search_field :name_cont, class: 'form-control' %>
        <span class="input-group-btn">
          <button class="btn btn-primary">Search <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-5 ">
    <%= paginate @product_features %>
  </div>
  
</row>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Product</th>
      <th>Pfeature</th>
      <th>Active status</th>
      <th>Sort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_features.each do |product_feature| %>
      <tr>
        <td><%= product_feature.name %></td>
        <td><%= product_feature.product %></td>
        <td><%= product_feature.pfeature %></td>
        <td><%= product_feature.active_status %></td>
        <td><%= product_feature.sort %></td>
        <td><%= link_to 'Show', product_feature %></td>
        <td><%= link_to 'Edit', edit_product_feature_path(product_feature) %></td>
        <td><%= link_to 'Destroy', product_feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product feature', new_product_feature_path %>

app/views/product_features/new.html.erb
<h1>New Product Feature</h1>

<%= render 'form' %>

<%= link_to 'Back', product_features_path %>

app/views/product_features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_feature.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_feature.product %>
</p>

<p>
  <strong>Pfeature:</strong>
  <%= @product_feature.pfeature %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @product_feature.active_status %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @product_feature.sort %>
</p>

<%= link_to 'Edit', edit_product_feature_path(@product_feature) %> |
<%= link_to 'Back', product_features_path %>