config/routes.rb
Rails.application.routes.draw do
 
  resources :product_features
  resources :pfeatures
  resources :products
  resources :roles
  
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "home#index"

  get 'home/index'

  get 'home/about'

end

app/models/pfeature.rb
class Pfeature < ActiveRecord::Base
end

app/controllers/pfeatures_controller.rb
class PfeaturesController < ApplicationController
  before_action :set_pfeature, only: [:show, :edit, :update, :destroy]

  #cancancan
  load_and_authorize_resource

  # GET /pfeatures
  def index
    # @pfeatures = Pfeature.all
    @q = Pfeature.search(params[:q]) 
    @pfeatures = @q.result.page(params[:page])
  end

  # GET /pfeatures/1
  def show
  end

  # GET /pfeatures/new
  def new
    @pfeature = Pfeature.new
  end

  # GET /pfeatures/1/edit
  def edit
  end

  # POST /pfeatures
  def create
    @pfeature = Pfeature.new(pfeature_params)

    if @pfeature.save
      redirect_to @pfeature, notice: 'Pfeature was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pfeatures/1
  def update
    if @pfeature.update(pfeature_params)
      redirect_to @pfeature, notice: 'Pfeature was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pfeatures/1
  def destroy
    @pfeature.destroy
    redirect_to pfeatures_url, notice: 'Pfeature was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pfeature
      @pfeature = Pfeature.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pfeature_params
      params.require(:pfeature).permit(:name, :fdate, :active_status, :sort)
    end
end

app/helpers/pfeatures_helper.rb
module PfeaturesHelper
end

app/views/pfeatures/_form.html.erb
<%= simple_form_for(@pfeature) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :fdate %>
    <%= f.input :active_status %>
    <%= f.input :sort %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pfeatures/edit.html.erb
<h1>Editing Pfeature</h1>

<%= render 'form' %>

<%= link_to 'Show', @pfeature %> |
<%= link_to 'Back', pfeatures_path %>

app/views/pfeatures/index.html.erb
<p id="notice"><%= notice %></p>

<row>

  <div class="col-sm-2 ">
    <h3>Listing Pfeatures</h3>
  </div>

  <div class="col-sm-3 col-sm-offset-1">
    <%= search_form_for @q, class: 'search-form' do |f| %>
      <div class="input-group">
        <%= f.search_field :name_cont, class: 'form-control' %>
        <span class="input-group-btn">
          <button class="btn btn-primary">Search <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-5 ">
    <%= paginate @pfeatures %>
  </div>
  
</row>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Fdate</th>
      <th>Active status</th>
      <th>Sort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pfeatures.each do |pfeature| %>
      <tr>
        <td><%= pfeature.name %></td>
        <td><%= pfeature.fdate %></td>
        <td><%= pfeature.active_status %></td>
        <td><%= pfeature.sort %></td>
        <td><%= link_to 'Show', pfeature %></td>
        <td><%= link_to 'Edit', edit_pfeature_path(pfeature) %></td>
        <td><%= link_to 'Destroy', pfeature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pfeature', new_pfeature_path %>

app/views/pfeatures/new.html.erb
<h1>New Pfeature</h1>

<%= render 'form' %>

<%= link_to 'Back', pfeatures_path %>

app/views/pfeatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pfeature.name %>
</p>

<p>
  <strong>Fdate:</strong>
  <%= @pfeature.fdate %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @pfeature.active_status %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @pfeature.sort %>
</p>

<%= link_to 'Edit', edit_pfeature_path(@pfeature) %> |
<%= link_to 'Back', pfeatures_path %>